apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-site-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    # FIXME: use the right IP
    server: 10.10.135.148
    path: "/data/site"
